name: Build and test

on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6.3.0
          with:
            node-version: '24'

      - run: |
          yarn install --frozen-lockfile

      - run: |
          yarn all
